### ISSUE TITLE
RESOLVED-- NEED 3.6.x OR HIGHER FW-- CLI [Object Object] screen upon loading with helio v1 on butterflight 3.5.3

### ISSUE THREAD

**Issue by tnap1979** [heliorc/pegasus-ui#1]
i have a helio v1, on butterflight 3.5.3 imuf 1.1.0, and i get this CLI screen upon loading of pegasus that just says [object object]
in the upper left hand screen

NVM... RESOLVED... i have to be on 3.6.x or higher firmware :D
sorry for the post ;)

**Comment by orneryd** [comment]
No worries!
