### ISSUE TITLE
missing targets and FW in Pegasus 0.1.11

### ISSUE THREAD

**Issue by oyvinla** [heliorc/pegasus-ui#10]
Pegasus GUI 0.1.11 OSX

Matek F411 and more targets are missing and not able to find BuF V3.6.1

<img width="1023" alt="screenshot 2018-10-25 at 19 39 49" src="https://user-images.githubusercontent.com/21168360/47519529-0bd0f780-d88e-11e8-9560-828f4ec74f56.png">

<img width="1020" alt="screenshot 2018-10-25 at 19 44 17" src="https://user-images.githubusercontent.com/21168360/47519687-636f6300-d88e-11e8-8501-1e65b3881a7b.png">

**Comment by orneryd** [comment]
Is this still the case for 0.1.12/ Buf 3.6.2?

**Comment by oyvinla** [comment]
with 0.1.12 I cant find any targets at all when connecting the matek F411. The "select a target" pulldown menu doesnt work. same issue on both windows and OSX

**Comment by orneryd** [comment]
the targets should be updated, Thanks @apocolipse!
