### ISSUE TITLE
Field descriptions are not visible only variables.

### ISSUE THREAD

**Issue by lutek** [heliorc/pegasus-ui#11]
**Describe the bug**
no default language, on systems other than English (Polish). Field descriptions are not visible only variables.

**Expected behavior**
default english

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/846598/47613860-a9971300-da96-11e8-8216-4f98c74c7f70.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by orneryd** [comment]
I will add a polish stub to make sure we get that translated.

**Comment by Handieman2** [comment]
I have the same problem with missing field descriptions. I can not read the cpu usage because of it.
![2018-11-10](https://user-images.githubusercontent.com/25963028/48303118-8cd2f480-e506-11e8-9b5c-27e654675f90.png)

**Comment by orneryd** [comment]
can you try 0.2.0 from the drive? https://drive.google.com/drive/u/0/folders/1VsQEW_FQXVkZ2V02wH7hL6KBkbbTSGdz

**Comment by lutek** [comment]
it's good.
