### ISSUE TITLE
Motor direction graphic not reversed when motors reversed

### ISSUE THREAD

**Issue by cemtait** [heliorc/pegasus-ui#18]
The graphic displayed on the screen (in the "Spin motors" page), is motors NOT reversed, when motors are running in reverse.

**To Reproduce**
1. Go to 'Motor assistant page'
2. Select "reversed" by clicking on the graphic on the right
3. On the next page, you are now looking at a graphic with normal motor direction.

**Expected behavior**
The motors have been reversed which is expected.  But displaying the wrong graphic is confusing.

**Comment by orneryd** [comment]
this is fixed in 0.2.0
