### ISSUE TITLE
Doesn't work with BuF

### ISSUE THREAD

**Issue by spatzengr** [heliorc/pegasus-ui#5]
SpracingF3 board not detected (with BuF 3.5.1 flashed to it).  Notes say for more than Helio.  Is that correct?  I ask cause maybe that is by design that it doesn't detect.  IDK.

![image](https://user-images.githubusercontent.com/25570978/46672720-29237780-cba6-11e8-91da-8453a1e48cf4.png)

![image](https://user-images.githubusercontent.com/25570978/46672860-89b2b480-cba6-11e8-8b8f-a8993b5e41b0.png)

**Comment by orneryd** [comment]
it's only compatible with 3.6.0+

**Comment by spatzengr** [comment]
@orneryd , I have 3.6.0 flashed.  Build this AM.

![image](https://user-images.githubusercontent.com/25570978/46686267-c346e800-cbc5-11e8-9958-1f63f4c55a41.png)

**Comment by orneryd** [comment]
It doesn't look like the SPF3 is in the list of currently supported versions as mentioned in the original post.
![image](https://user-images.githubusercontent.com/1736223/46694515-ed96a680-cbc1-11e8-8223-8de614c57ab2.png)

**Comment by rs2k** [comment]
@spatzengr, you should upgrade to a supported flight controller.

**Comment by spatzengr** [comment]
Oh, missed that.  Is that in the GitHub?  Appologies as it didn't jump out at me.  The SPf3 is my test board.  I have a RevoltOSD though.  So I can give that a whirl eventually.

So no OmnibusF4SD or SPracingF7Dual?  Maybe evenutally eh?
