### ISSUE TITLE
Proshot not working

### ISSUE THREAD

**Issue by Clynikal** [heliorc/pegasus-ui#7]
On BuF & pegasus 3.6 proshot does not work,

Motor 4 spins in 0CW only.
Pass through to Blheli32 suite is also affected with motor 4 again only working on pass through.

Motors tab: Only motor 4 spins with proshot selected, when you select another protocol all motors spin.

All other protocols are ok

**Comment by orneryd** [comment]
This is a bug report for the Butterflight team. I would suggest posting it there.
