### ISSUE TITLE
Soft Bootload for down rev not working

### ISSUE THREAD

**Issue by Clynikal** [heliorc/pegasus-ui#9]
I'm not certain this is a pegasus thing but if you try to down rev in pegasus you get pushed to cli and no typing entry is enabled to BL/FLASH

Similarly in BuF 3.6 I had to manually bridge the F4 pins to enter bootload after trying every possible USB driver solution. This was only for trying to rev back to 3.5.2.

**Comment by orneryd** [comment]
does this persist on 0.1.12?

**Comment by orneryd** [comment]
the cli should work properly in 0.2.0 for older versions of BxF now.
